---
title: "STA 315 2.0 Essential Skills in Statistics"
---

# Course Information

To access important information regarding the unit, please go to the Google Classroom of the unit.

# Course outline

Avalilable in the Google Classroom

# Lecture Schedule

## Lecture 1: 22 November 2024

[Slides 1](https://thiyangt.github.io/ES1/#/title-slide)

## Lecture 2: 29 November 2024

[Slides 2](/Week2/index.html)

## Lecture 3: 6 December 2024

[Slides 3](https://thiyanga-scientificwriting.netlify.app/slides/1_thesiswriting/main#1)

## Lecture 4: 13 December 2024

[Slides 4](/Week4/index.html)

Data: Access the dataset named `srilanka_weekly_data` using the app provided below.

<https://denguedatahub.shinyapps.io/denguedatahub/>

Assignment 1: denguedata visualisations

## Lecture 5: 20 December 2024

[Slides 5](/Week5/index.html)

Assignment 1 - Feedback - [Students' Answers](/Feedback/f1.pdf)

## Lecture 6: 3 January 2025

[Slides 6](/Week6/index.html)

## Lecture 7: 10 January 2025

[In-class discussion problems](/Week7/2024_ES.pdf)

## Lecture 8: 17 January 2025

Mid-semester Examination (Lecture 1- Lecture 6)

## Lecture 9: 24 January 2025

[Slides 8](/Week8/index.html)

Common Errors Made by Students in STA 113 2.0 Descriptive Statistics: Key Essential Skills

## Lecture 10: 31 January 2025

[Slides 9](/Week9/index.html)

## Lecture 11: 7 February 2025

[Design and Analysis of Experiments](/Week11/DOE.pdf)

## Lecture 12: 14 February 2025

Kaggle Class Competition

## Lecture 13: 21 February 2025

[Emerging trends and technologies in Statistics and Data Science](/Week13/index.html)

[Video](https://youtu.be/WGF1mQDKQUY?feature=shared)
